/*
 * tase2_version.h
 */

#ifndef SRC_TASE2_COMMON_TASE2_VERSION_H_CMAKE_
#define SRC_TASE2_COMMON_TASE2_VERSION_H_CMAKE_

#define TASE2_LIBRARY_VERSION_MAJOR ${TASE2_LIB_VERSION_MAJOR}
#define TASE2_LIBRARY_VERSION_MINOR ${TASE2_LIB_VERSION_MINOR}
#define TASE2_LIBRARY_VERSION_PATCH ${TASE2_LIB_VERSION_PATCH}
#define TASE2_LIBRARY_VERSION_STRING "${TASE2_LIB_VERSION_MAJOR}.${TASE2_LIB_VERSION_MINOR}.${TASE2_LIB_VERSION_PATCH}"

#endif /* SRC_TASE2_COMMON_TASE2_VERSION_H_CMAKE_ */
