//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 07-09-05 02:20 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    [Serializable()]
    public class StringCollection : System.Collections.CollectionBase
    {
        
        public StringCollection()
        {
        }
        
        public string this[int idx]
        {
            get
            {
                return ((string)(base.InnerList[idx]));
            }
            set
            {
                base.InnerList[idx] = value;
            }
        }
        
        public int Add(string value)
        {
            return base.InnerList.Add(value);
        }
        
        public int IndexOf(string value)
        {
            return base.InnerList.IndexOf(value);
        }
        
        public void Insert(int index, string value)
        {
            base.InnerList.Insert(index, value);
        }
        
        public void Remove(string value)
        {
            base.InnerList.Remove(value);
        }
        
        public bool Contains(string value)
        {
            return base.InnerList.Contains(value);
        }
    }
}
