//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 11-10-05 10:01 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/messages/1.0/", TypeName="submitTimeSeriesResponse")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    [Serializable()]
    public class SubmitTimeSeriesResponse
    {
        
        /// <remarks/>
        private string messageID;
        
        /// <remarks/>
        private string referringMessageID;
        
        /// <remarks/>
        private StatusType status;
        
        /// <remarks/>
        private StringCollection statusMessage;
        
        /// <remarks/>
        private TimeSeriesResponseTypeCollection setOfTimeSeriesResponse;
        
        public SubmitTimeSeriesResponse()
        {
        }
        
        public SubmitTimeSeriesResponse(string messageID, string referringMessageID, StatusType status, StringCollection statusMessage, TimeSeriesResponseTypeCollection setOfTimeSeriesResponse)
        {
            this.messageID = messageID;
            this.referringMessageID = referringMessageID;
            this.status = status;
            this.statusMessage = statusMessage;
            this.setOfTimeSeriesResponse = setOfTimeSeriesResponse;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MessageID")]
        public string MessageID
        {
            get
            {
                return this.messageID;
            }
            set
            {
                this.messageID = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ReferringMessageID")]
        public string ReferringMessageID
        {
            get
            {
                return this.referringMessageID;
            }
            set
            {
                this.referringMessageID = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Status")]
        public StatusType Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("StatusMessage")]
        public StringCollection StatusMessage
        {
            get
            {
                return this.statusMessage;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("StatusMessage");
                }
                this.statusMessage = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("TimeSeriesResponse", Namespace="http://www.powel.no/icc/ws/tsws/data/1.0/", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="SetOfTimeSeriesResponse")]
        public TimeSeriesResponseTypeCollection SetOfTimeSeriesResponse
        {
            get
            {
                return this.setOfTimeSeriesResponse;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("SetOfTimeSeriesResponse");
                }
                this.setOfTimeSeriesResponse = value;
            }
        }
    }
}
