//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 11-10-05 10:01 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <summary>
    /// Detailed import status for a time series
    /// </summary>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/data/1.0/", TypeName="TimeSeriesResponseType")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    [Serializable()]
    public class TimeSeriesResponseType
    {
        
        /// <remarks/>
        private TsReferenceType reference;
        
        /// <remarks/>
        private StatusType status;
        
        /// <remarks/>
        private bool statusSpecified;
        
        /// <remarks/>
        private StringCollection statusMessage;
        
        /// <remarks/>
        private TsItemsResponseTypeCollection itemsResponse;
        
        /// <remarks/>
        private string tsID;
        
        /// <remarks/>
        private TsResponseLevelType responseLevel = TsResponseLevelType.NONE;
        
        public TimeSeriesResponseType()
        {
        }
        
        public TimeSeriesResponseType(TsReferenceType reference, StatusType status, bool statusSpecified, StringCollection statusMessage, TsItemsResponseTypeCollection itemsResponse, string tsID, TsResponseLevelType responseLevel)
        {
            this.reference = reference;
            this.status = status;
            this.statusSpecified = statusSpecified;
            this.statusMessage = statusMessage;
            this.itemsResponse = itemsResponse;
            this.tsID = tsID;
            this.responseLevel = responseLevel;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Reference")]
        public TsReferenceType Reference
        {
            get
            {
                return this.reference;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Reference");
                }
                this.reference = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Status")]
        public StatusType Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusSpecified;
            }
            set
            {
                this.statusSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("StatusMessage")]
        public StringCollection StatusMessage
        {
            get
            {
                return this.statusMessage;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("StatusMessage");
                }
                this.statusMessage = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsResponse")]
        public TsItemsResponseTypeCollection ItemsResponse
        {
            get
            {
                return this.itemsResponse;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ItemsResponse");
                }
                this.itemsResponse = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="TsID")]
        public string TsID
        {
            get
            {
                return this.tsID;
            }
            set
            {
                this.tsID = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ResponseLevel")]
        [System.ComponentModel.DefaultValueAttribute(TsResponseLevelType.NONE)]
        public TsResponseLevelType ResponseLevel
        {
            get
            {
                return this.responseLevel;
            }
            set
            {
                this.responseLevel = value;
            }
        }
    }
}
