//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 11-10-05 10:03 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <summary>
    /// Standard time series
    /// </summary>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/data/1.0/", TypeName="TimeSeries")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    [Serializable()]
    public class TimeSeriesType
    {
        
        /// <remarks/>
        private TsReferenceType reference;
        
        /// <remarks/>
        private TsValueMetaInfoType valueMetaInfo;
        
        /// <remarks/>
        private TsPVQItemTypeCollection items;
        
        /// <remarks/>
        private string tsID;
        
        /// <remarks/>
        private TsResponseLevelType responseLevel = TsResponseLevelType.NONE;
        
        public TimeSeriesType()
        {
        }
        
        public TimeSeriesType(TsReferenceType reference, TsValueMetaInfoType valueMetaInfo, TsPVQItemTypeCollection items, string tsID, TsResponseLevelType responseLevel)
        {
            this.reference = reference;
            this.valueMetaInfo = valueMetaInfo;
            this.items = items;
            this.tsID = tsID;
            this.responseLevel = responseLevel;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Reference")]
        public TsReferenceType Reference
        {
            get
            {
                return this.reference;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Reference");
                }
                this.reference = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ValueMetaInfo")]
        public TsValueMetaInfoType ValueMetaInfo
        {
            get
            {
                return this.valueMetaInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ValueMetaInfo");
                }
                this.valueMetaInfo = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("PVQItem", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Items")]
        public TsPVQItemTypeCollection Items
        {
            get
            {
                return this.items;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Items");
                }
                this.items = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="TsID")]
        public string TsID
        {
            get
            {
                return this.tsID;
            }
            set
            {
                this.tsID = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ResponseLevel")]
        [System.ComponentModel.DefaultValueAttribute(TsResponseLevelType.NONE)]
        public TsResponseLevelType ResponseLevel
        {
            get
            {
                return this.responseLevel;
            }
            set
            {
                this.responseLevel = value;
            }
        }
    }
}
