//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 14-10-05 09#49 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;
    
    
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="TimeSeriesResponseWS", Namespace="http://www.powel.no/icc/ws")]
	public class TimeSeriesResponseWSPort : System.Web.Services.Protocols.SoapHttpClientProtocol, ITimeSeriesResponseWSPort
	{
        
		/// <remarks/>
		public TimeSeriesResponseWSPort()
		{
		}
        
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.powel.no/icc/ws:submitTimeSeriesResponseIn", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		public void SubmitTimeSeriesResponse([System.Xml.Serialization.XmlElementAttribute("submitTimeSeriesResponse", Namespace="http://www.powel.no/icc/ws/tsws/messages/1.0/")] SubmitTimeSeriesResponse submitTimeSeriesResponse1)
		{
			this.Invoke("SubmitTimeSeriesResponse", new object[] {
																	 submitTimeSeriesResponse1});
		}
        
		/// <remarks/>
		public System.IAsyncResult BeginsubmitTimeSeriesResponse([System.Xml.Serialization.XmlElementAttribute(ElementName="submitTimeSeriesResponse1")] SubmitTimeSeriesResponse submitTimeSeriesResponse1, [System.Xml.Serialization.XmlElementAttribute(ElementName="callback")] System.AsyncCallback callback, [System.Xml.Serialization.XmlElementAttribute(ElementName="asyncState")] object asyncState)
		{
			return this.BeginInvoke("BeginsubmitTimeSeriesResponse", new object[] {
																					  submitTimeSeriesResponse1}, callback, asyncState);
		}
        
		/// <remarks/>
		public void EndsubmitTimeSeriesResponse([System.Xml.Serialization.XmlElementAttribute(ElementName="asyncResult")] System.IAsyncResult asyncResult)
		{
			this.EndInvoke(asyncResult);
		}
	}    
}    

