//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 12-09-05 01:37 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/enums/1.0/", TypeName="TsCorMethodType")]
    [Serializable()]
    public enum TsCorMethodType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CONSTANT")]
        CONSTANT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="COPY")]
        COPY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="INTERPOLATE")]
        INTERPOLATE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EXTRAPOLATE")]
        EXTRAPOLATE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MEAN")]
        MEAN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MEAN_DELTA_TIME")]
        MEAN_DELTA_TIME,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ENERGY")]
        ENERGY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="METER_SUM")]
        METER_SUM,
    }
}
