//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 07-09-05 02:20 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/enums/1.0/", TypeName="TsIntervalType")]
    [Serializable()]
    public enum TsIntervalType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MIN15")]
        MIN15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HOUR")]
        HOUR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DAY")]
        DAY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WEEK")]
        WEEK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MONTH")]
        MONTH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="YEAR")]
        YEAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MOMENTUM")]
        MOMENTUM,
    }
}
