//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 07-09-05 02:20 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <summary>
    /// Detailed import status for a collection of time series values
    /// </summary>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/data/1.0/", TypeName="TsItemsResponseType")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    [Serializable()]
    public class TsItemsResponseType
    {
        
        /// <remarks/>
        private TsPVQItemType tsPVQItem;
        
        /// <remarks/>
        private StatusType status;
        
        /// <remarks/>
        private bool statusSpecified;
        
        /// <remarks/>
        private string statusMessage;
        
        public TsItemsResponseType()
        {
        }
        
        public TsItemsResponseType(TsPVQItemType tsPVQItem, StatusType status, bool statusSpecified, string statusMessage)
        {
            this.tsPVQItem = tsPVQItem;
            this.status = status;
            this.statusSpecified = statusSpecified;
            this.statusMessage = statusMessage;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="TsPVQItem")]
        public TsPVQItemType TsPVQItem
        {
            get
            {
                return this.tsPVQItem;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("TsPVQItem");
                }
                this.tsPVQItem = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Status")]
        public StatusType Status
        {
            get
            {
                return this.status;
            }
            set
            {
                this.status = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusSpecified;
            }
            set
            {
                this.statusSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="StatusMessage")]
        public string StatusMessage
        {
            get
            {
                return this.statusMessage;
            }
            set
            {
                this.statusMessage = value;
            }
        }
    }
}
