//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 07-09-05 02:20 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    [Serializable()]
    public class TsPVQItemTypeCollection : System.Collections.CollectionBase
    {
        
        public TsPVQItemTypeCollection()
        {
        }
        
        public TsPVQItemType this[int idx]
        {
            get
            {
                return ((TsPVQItemType)(base.InnerList[idx]));
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("value");
                }
                base.InnerList[idx] = value;
            }
        }
        
        public int Add(TsPVQItemType value)
        {
            if ((value == null))
            {
                throw new System.ArgumentNullException("value");
            }
            return base.InnerList.Add(value);
        }
        
        public int IndexOf(TsPVQItemType value)
        {
            if ((value == null))
            {
                throw new System.ArgumentNullException("value");
            }
            return base.InnerList.IndexOf(value);
        }
        
        public void Insert(int index, TsPVQItemType value)
        {
            if ((value == null))
            {
                throw new System.ArgumentNullException("value");
            }
            base.InnerList.Insert(index, value);
        }
        
        public void Remove(TsPVQItemType value)
        {
            if ((value == null))
            {
                throw new System.ArgumentNullException("value");
            }
            base.InnerList.Remove(value);
        }
        
        public bool Contains(TsPVQItemType value)
        {
            if ((value == null))
            {
                throw new System.ArgumentNullException("value");
            }
            return base.InnerList.Contains(value);
        }
    }
}
