//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 18-08-05 11:15 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216
// --------------------------------
// Edited 01.sep 2005 in order to save datetime information during import, because of data loss during automatic conversion to localtime.


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
	using Powel.Icc.Services.Time;
	using Powel.Xml;
	using System.Globalization;
    
    
    /// <summary>
    /// Properties necessary to identify a time series
    /// </summary>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/data/1.0/", TypeName="TsReferenceType")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    [Serializable()]
    public class TsReferenceType
    {
        
        /// <remarks/>
        private string iD;
        
        /// <remarks/>
        private string originator;
        
        /// <remarks/>
        private UtcTime originatorSendingTime;
        
        public TsReferenceType()
        {
        }
        
        public TsReferenceType(string iD, string originator, UtcTime originatorSendingTime)
        {
            this.iD = iD;
            this.originator = originator;
            this.originatorSendingTime = originatorSendingTime;
        }
        
        /// <summary>
        /// External reference describing the time series
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ID")]
        public string ID
        {
            get
            {
                return this.iD;
            }
            set
            {
                this.iD = value;
            }
        }
        
        /// <summary>
        /// Originator of time series
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Originator")]
        public string Originator
        {
            get
            {
                return this.originator;
            }
            set
            {
                this.originator = value;
            }
        }
        
        /// <summary>
        /// Time of sending from originator
        /// </summary>
        [XmlIgnore()]
		public UtcTime OriginatorSendingTimeDateTime
        {
            get
            {
                return this.originatorSendingTime;
            }
            set
            {
                this.originatorSendingTime = value;
            }
        }

		[System.Xml.Serialization.XmlElementAttribute(ElementName="OriginatorSendingTime")]
		public string OriginatorSendingTime
		{
			get
			{
				return originatorSendingTime.ToXmlDateTime();
			}
			set
			{
				this.originatorSendingTime = XmlUtil.ParseDate(value);
			}
		}

    }
}
