//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 18-08-05 11:16 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216
// --------------------------------
// Edited 01.sep 2005 in order to save datetime information during import, because of data loss during automatic conversion to localtime.


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
	using Powel.Icc.Services.Time;
	using Powel.Xml;
	using System.Globalization;
    
    
    /// <summary>
    /// Type describing a time period
    /// </summary>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/data/1.0/", TypeName="TsTimePeriodType")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    [Serializable()]
    public class TsTimePeriodType
    {
        
        /// <remarks/>
        private UtcTime from;
        
        /// <remarks/>
        private UtcTime to;
        
        /// <remarks/>
        private bool toSpecified;
        
        /// <remarks/>
        private string duration;
        
        public TsTimePeriodType()
        {
        }
        
        public TsTimePeriodType(UtcTime from, UtcTime to, bool toSpecified, string duration)
        {
            this.from = from;
            this.to = to;
            this.toSpecified = toSpecified;
            this.duration = duration;
        }
        
        //[System.Xml.Serialization.XmlAttributeAttribute(AttributeName="From")]
		[XmlIgnore()]
        public UtcTime FromDateTime
        {
            get
            {
                return this.from;
            }
            set
            {
                this.from = value;
            }
        }

		[System.Xml.Serialization.XmlAttributeAttribute(AttributeName="From")]
		public string From
		{
			get
			{
				return from.ToXmlDateTime();
			}
			set
			{
				this.from = XmlUtil.ParseDate(value);
			}
		}
        

        //[System.Xml.Serialization.XmlAttributeAttribute(AttributeName="To")]
		[XmlIgnore()]
        public UtcTime ToDateTime
        {
            get
            {
                return this.to;
            }
            set
            {
                this.to = value;
            }
        }

		[System.Xml.Serialization.XmlAttributeAttribute(AttributeName="To")]
		public string To
		{
			get
			{
				return to.ToXmlDateTime();
			}
			set
			{
				this.to = XmlUtil.ParseDate(value);
			}
		}
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified
        {
            get
            {
                return this.toSpecified;
            }
            set
            {
                this.toSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration", AttributeName="Duration")]
        public string Duration
        {
            get
            {
                return this.duration;
            }
            set
            {
                this.duration = value;
            }
        }
    }
}
