//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 07-09-05 02:20 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.TimeSeries.TimeSeriesXML
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <summary>
    /// Metainfo describing how to parse time series values
    /// </summary>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.powel.no/icc/ws/tsws/data/1.0/", TypeName="TsValueMetaInfoType")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    [Serializable()]
    public class TsValueMetaInfoType
    {
        
        /// <remarks/>
        private string measurementUnit;
        
        /// <remarks/>
        private TsIntervalType interval;
        
        /// <remarks/>
        private bool intervalSpecified;
        
        /// <remarks/>
        private TsTimePeriodType replacePeriod;
        
        public TsValueMetaInfoType()
        {
        }
        
        public TsValueMetaInfoType(string measurementUnit, TsIntervalType interval, bool intervalSpecified, TsTimePeriodType replacePeriod)
        {
            this.measurementUnit = measurementUnit;
            this.interval = interval;
            this.intervalSpecified = intervalSpecified;
            this.replacePeriod = replacePeriod;
        }
        
        /// <summary>
        /// Unit of measurement for time series values, e.g. kW, m/s
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MeasurementUnit")]
        public string MeasurementUnit
        {
            get
            {
                return this.measurementUnit;
            }
            set
            {
                this.measurementUnit = value;
            }
        }
        
        /// <summary>
        /// Interval of supplied time series values
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Interval")]
        public TsIntervalType Interval
        {
            get
            {
                return this.interval;
            }
            set
            {
                this.interval = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IntervalSpecified
        {
            get
            {
                return this.intervalSpecified;
            }
            set
            {
                this.intervalSpecified = value;
            }
        }
        
        /// <summary>
        /// Specifies time period that shall be deleted and potentially replaced by submitted time series values. Replace period may be shorter than or longer than (or even outside of) period of submitted time series values. Existing time series values in Replace Period will be deleted before storage of submitted values.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ReplacePeriod")]
        public TsTimePeriodType ReplacePeriod
        {
            get
            {
                return this.replacePeriod;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ReplacePeriod");
                }
                this.replacePeriod = value;
            }
        }
    }
}
