//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 25-09-06 09:57 
//
// This source code was auto-generated by WsContractFirst, Version=0.5.1.5216


namespace Powel.Icc.Messaging.EmbeddedTextMessageXml
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <summary></summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmbeddedTextMessage", Namespace="http://www.powel.no/icc/messaging")]
    public class EmbeddedTextMessage : System.Web.Services.Protocols.SoapHttpClientProtocol, IEmbeddedTextMessage
    {
        
        /// <remarks/>
        public EmbeddedTextMessage()
        {
        }
        
        /// <summary></summary>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.powel.no/icc/messaging:sendEmbeddedTextMessageIn", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SendEmbeddedTextMessage([System.Xml.Serialization.XmlElementAttribute("sendEmbeddedTextMessage", Namespace="http://tempuri.org/GS2Message.xsd")] SendEmbeddedTextMessage sendEmbeddedTextMessage1)
        {
            this.Invoke("SendEmbeddedTextMessage", new object[] {
                        sendEmbeddedTextMessage1});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendEmbeddedTextMessage([System.Xml.Serialization.XmlElementAttribute(ElementName="sendEmbeddedTextMessage1")] SendEmbeddedTextMessage sendEmbeddedTextMessage1, [System.Xml.Serialization.XmlElementAttribute(ElementName="callback")] System.AsyncCallback callback, [System.Xml.Serialization.XmlElementAttribute(ElementName="asyncState")] object asyncState)
        {
            return this.BeginInvoke("BeginsendEmbeddedTextMessage", new object[] {
                        sendEmbeddedTextMessage1}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndsendEmbeddedTextMessage([System.Xml.Serialization.XmlElementAttribute(ElementName="asyncResult")] System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/GS2Message.xsd", TypeName="sendEmbeddedTextMessage")]
    public class SendEmbeddedTextMessage
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="id")]
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="messageType")]
        public string MessageType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="text")]
        public string Text;
        
        public SendEmbeddedTextMessage()
        {
        }
        
        public SendEmbeddedTextMessage(string id, string messageType, string text)
        {
            this.Id = id;
            this.MessageType = messageType;
            this.Text = text;
        }
    }
}
