//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Powel.Icc.Messaging2.MeteringXML;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.powel.no/icc/ws/metering/data/1.5/", ClrNamespace="www.powel.no.icc.ws.metering.data._1._51")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.powel.no/icc/ws/metering/enums/1.5/", ClrNamespace="www.powel.no.icc.ws.metering.enums._1._51")]

namespace Powel.Icc.Messaging2
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.powel.no/icc/ws/metering/data/1.5/", ConfigurationName="IResponseService")]
    public interface IResponseService
    {
        
        // CODEGEN: Generating message contract since element name response from namespace http://www.powel.no/icc/ws/metering/data/1.5/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.powel.no/icc/ws/metering/data/1.5/IResponseService/responseType")]
        void SendResponse(SendResponse request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.powel.no/icc/ws/metering/messages/1.5/) of message submitInstallationResponse does not match the default value (http://www.powel.no/icc/ws/metering/data/1.5/)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.powel.no/icc/ws/metering/data/1.5/IResponseService/submitInstallationR" +
            "esponse")]
        void SubmitInstallationResponse(submitInstallationResponse request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.powel.no/icc/ws/metering/messages/1.5/) of message submitComponentsResponse does not match the default value (http://www.powel.no/icc/ws/metering/data/1.5/)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.powel.no/icc/ws/metering/data/1.5/IResponseService/submitComponentsRes" +
            "ponse")]
        void SubmitComponentsResponse(submitComponentsResponse request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.powel.no/icc/ws/metering/messages/1.5/) of message submitRegistersResponse does not match the default value (http://www.powel.no/icc/ws/metering/data/1.5/)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.powel.no/icc/ws/metering/data/1.5/IResponseService/submitRegistersResp" +
            "onse")]
        void SubmitRegistersResponse(submitRegistersResponse request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.powel.no/icc/ws/metering/messages/1.5/) of message submitExportsResponse does not match the default value (http://www.powel.no/icc/ws/metering/data/1.5/)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.powel.no/icc/ws/metering/data/1.5/IResponseService/submitExportsRespon" +
            "se")]
        void SubmitExportsResponse(submitExportsResponse request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendResponse", Namespace="http://www.powel.no/icc/ws/metering/data/1.5/", Order=0)]
        public SendResponseBody Body;
        
        public SendResponse()
        {
        }
        
        public SendResponse(SendResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.powel.no/icc/ws/metering/data/1.5/")]
    public partial class SendResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ResponseType response;
        
        public SendResponseBody()
        {
        }
        
        public SendResponseBody(ResponseType response)
        {
            this.response = response;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IResponseServiceChannel : IResponseService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public class ResponseServiceClient : System.ServiceModel.ClientBase<IResponseService>, IResponseService
    {

        public ResponseServiceClient()
        {
        }

        public ResponseServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ResponseServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ResponseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ResponseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void IResponseService.SendResponse(SendResponse request)
        {
            Channel.SendResponse(request);
        }

        public void SendResponse(ResponseType response)
        {
            var inValue = new SendResponse { Body = new SendResponseBody { response = response } };
            ((IResponseService)(this)).SendResponse(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void IResponseService.SubmitInstallationResponse(submitInstallationResponse request)
        {
            Channel.SubmitInstallationResponse(request);
        }

        public void SubmitInstallationResponse(string messageID, string referringMessageID, StatusType status, string statusCode, string statusMessage)
        {
            var inValue = new submitInstallationResponse
                              {
                                  messageID = messageID,
                                  referringMessageID = referringMessageID,
                                  status = status,
                                  statusCode = statusCode,
                                  statusMessage = statusMessage
                              };
            ((IResponseService)(this)).SubmitInstallationResponse(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void IResponseService.SubmitComponentsResponse(submitComponentsResponse request)
        {
            Channel.SubmitComponentsResponse(request);
        }

        public void SubmitComponentsResponse(string messageID, string referringMessageID, StatusType status, string statusCode, string statusMessage)
        {
            var inValue = new submitComponentsResponse
                              {
                                  messageID = messageID,
                                  referringMessageID = referringMessageID,
                                  status = status,
                                  statusCode = statusCode,
                                  statusMessage = statusMessage
                              };
            ((IResponseService)(this)).SubmitComponentsResponse(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void IResponseService.SubmitRegistersResponse(submitRegistersResponse request)
        {
            Channel.SubmitRegistersResponse(request);
        }

        public void SubmitRegistersResponse(string messageID, string referringMessageID, StatusType status, string statusCode, string statusMessage)
        {
            var inValue = new submitRegistersResponse
                              {
                                  messageID = messageID,
                                  referringMessageID = referringMessageID,
                                  status = status,
                                  statusCode = statusCode,
                                  statusMessage = statusMessage
                              };
            ((IResponseService)(this)).SubmitRegistersResponse(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void IResponseService.SubmitExportsResponse(submitExportsResponse request)
        {
            Channel.SubmitExportsResponse(request);
        }

        public void SubmitExportsResponse(string messageID, string referringMessageID, StatusType status, string statusCode, string statusMessage)
        {
            var inValue = new submitExportsResponse
                              {
                                  messageID = messageID,
                                  referringMessageID = referringMessageID,
                                  status = status,
                                  statusCode = statusCode,
                                  statusMessage = statusMessage
                              };
            ((IResponseService)(this)).SubmitExportsResponse(inValue);
        }
    }
}
