using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using NP.Auction.Client.Contracts;
using Powel.Icc.Data;
using Powel.Icc.Diagnostics;
using Powel.Icc.Messaging.DataExchangeCommon;
//using Powel.Icc.Messaging.DataExchangeCommon.Abstract;
using Powel.Icc.Messaging.DataExchangeManager.DataExchangeApi;
using Powel.Icc.Messaging.DataExchangeManager.NordPoolRequestCommand;

namespace Powel.Icc.Messaging.NpAuctionDataExchangeManager.Modules
{
    public class NpAuctionLogic : WsLogicBase
    {
        //private readonly IImportApplication _importApplication;
        public NpAuctionLogic(Func<IDataExchangeApi> dataExchangeApiFactory, IServiceEventLogger serviceEventLogger/*, IImportApplication importApplication*/)
            : base(dataExchangeApiFactory, serviceEventLogger)
        {
            //_importApplication = importApplication;
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, Auction auction)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = Guid.NewGuid().ToString(),
                Protocol = DataExchangeMessageBase.ProtocolNpAuction,
                ProtocolId = (int)TsProtocol.NP_AUCTION,
                MessageData = JsonConvert.SerializeObject(auction),
                // switch sender and receiver from what was generated by NpAuctionRequester.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            base.SubmitImport(importMessage,null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, IEnumerable<Auction> auctions)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = Guid.NewGuid().ToString(),
                Protocol = DataExchangeMessageBase.ProtocolNpAuctions,
                ProtocolId = (int)TsProtocol.NP_AUCTION,
                MessageData = JsonConvert.SerializeObject(auctions),
                // switch sender and receiver from what was generated by NpAuctionRequester.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            base.SubmitImport(importMessage, null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, TradesSummary tradesSummary)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = Guid.NewGuid().ToString(),
                Protocol = DataExchangeMessageBase.ProtocolNpContract,
                ProtocolId = (int)TsProtocol.NP_TRADE,
                MessageData = JsonConvert.SerializeObject(tradesSummary),
                // switch sender and receiver from what was generated by NpAuctionRequester.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            base.SubmitImport(importMessage, null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, IEnumerable<TradesSummary> tradesSummaries)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = Guid.NewGuid().ToString(),
                Protocol = DataExchangeMessageBase.ProtocolNpContracts,
                ProtocolId = (int)TsProtocol.NP_TRADE,
                MessageData = JsonConvert.SerializeObject(tradesSummaries),
                // switch sender and receiver from what was generated by NpAuctionRequester.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            base.SubmitImport(importMessage, null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, CurveOrder curveOrder)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = exportCommand.MessageReference, // CurveOrder link back to the sent curve bid
                Protocol = DataExchangeMessageBase.ProtocolNpCurveOrder,
                ProtocolId = (int)TsProtocol.NP_CURVE_ORDER,
                // switch sender and receiver.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            importMessage.DeleteMessageData();  // Clear the link to the exportCommand.MessageData
            importMessage.SetMessageData(JsonConvert.SerializeObject(curveOrder));
            base.SubmitImport(importMessage, null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, BlockList blockOrder)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = exportCommand.MessageReference, // BlockOrder link back to the sent block bid
                Protocol = DataExchangeMessageBase.ProtocolNpBlockOrder,
                ProtocolId = (int)TsProtocol.NP_BLOCK_ORDER,
                // switch sender and receiver.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            importMessage.DeleteMessageData();  // Clear the link to the exportCommand.MessageData
            importMessage.SetMessageData(JsonConvert.SerializeObject(blockOrder));
            base.SubmitImport(importMessage, null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, OrdersResponse orders)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = Guid.NewGuid().ToString(),
                Protocol = DataExchangeMessageBase.ProtocolNpAuctionOrders,
                ProtocolId = (int)TsProtocol.NP_AUCTION_ORDERS,
                // switch sender and receiver.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            importMessage.DeleteMessageData();  // Clear the link to the exportCommand.MessageData
            importMessage.SetMessageData(JsonConvert.SerializeObject(orders));
            base.SubmitImport(importMessage, null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, PortfolioVolumesResponse response)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = Guid.NewGuid().ToString(),
                Protocol = DataExchangeMessageBase.ProtocolNpAuctionPortfolioVolumes,
                ProtocolId = (int)TsProtocol.NP_AUCTION_PORTFOLIO_VOLUMES,
                // switch sender and receiver.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            importMessage.DeleteMessageData();  // Clear the link to the exportCommand.MessageData
            importMessage.SetMessageData(JsonConvert.SerializeObject(response));
            base.SubmitImport(importMessage, null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, PricesResponse response)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = Guid.NewGuid().ToString(),
                Protocol = DataExchangeMessageBase.ProtocolNpAuctionPrices,
                ProtocolId = (int)TsProtocol.NP_AUCTION_PRICES,
                // switch sender and receiver.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            importMessage.DeleteMessageData();  // Clear the link to the exportCommand.MessageData
            importMessage.SetMessageData(JsonConvert.SerializeObject(response));
            base.SubmitImport(importMessage, null);
        }

        public virtual void SubmitImport(DataExchangeExportMessage exportCommand, NordPoolErrorMessage errorMsg)
        {
            var importMessage = new DataExchangeImportMessage(exportCommand)
            {
                ExternalReference = exportCommand.MessageReference, // Link back to the sent message (curve bid, block bid)
                Protocol = DataExchangeMessageBase.ProtocolNpErrorMessage,
                ProtocolId = (int)TsProtocol.NP_ERROR_MESSAGE,
                // switch sender and receiver.
                SenderId = exportCommand.ReceiverId,
                SenderName = exportCommand.ReceiverName,
                ReceiverId = exportCommand.SenderId,
                ReceiverName = exportCommand.SenderName
            };
            importMessage.DeleteMessageData();  // Clear the link to the exportCommand.MessageData
            importMessage.SetMessageData(JsonConvert.SerializeObject(errorMsg));
            base.SubmitImport(importMessage, null);
        }
    }
}
