/* Generated by lang2h , 19970929101538000	     */
#ifndef _DEFAULT_LOG_H_ 
#define ICC_OUT_OF_MEMORY 1 /* "No more memory availible for this process"  */
#define ICC_FILE_SYSTEM_FULL 2 /* "File system is full"  */
#define ICC_OUT_OF_PROCS 3 /* "No more processes availible"  */
#define UNKNOWN_MSG 4 /* "Unknown message specified : %d "  */
#define INPUT_ERROR 5 /* "General input error message"  */
#define DBI_ERROR_MESS 6 /* "Database error: %s"  */
#define CONTINUED_MESS 7 /* " %s"  */
#define GENERIC_MESS 8 /* "%s"  */
#endif /* _DEFAULT_LOG_H_ */
