//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mades.entsoe.eu/")]
    public partial class SendMessageError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorIDField;
        
        private string errorMessageField;
        
        private string receiverCodeField;
        
        private string errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("errorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string receiverCode {
            get {
                return this.receiverCodeField;
            }
            set {
                this.receiverCodeField = value;
                this.RaisePropertyChanged("receiverCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
                this.RaisePropertyChanged("errorDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mades.entsoe.eu/")]
    public partial class SentMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string receiverCodeField;
        
        private string businessTypeField;
        
        private byte[] contentField;
        
        private string senderApplicationField;
        
        private string baMessageIDField;
        
        private string baCorrelationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string receiverCode {
            get {
                return this.receiverCodeField;
            }
            set {
                this.receiverCodeField = value;
                this.RaisePropertyChanged("receiverCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string businessType {
            get {
                return this.businessTypeField;
            }
            set {
                this.businessTypeField = value;
                this.RaisePropertyChanged("businessType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string senderApplication {
            get {
                return this.senderApplicationField;
            }
            set {
                this.senderApplicationField = value;
                this.RaisePropertyChanged("senderApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string baMessageID {
            get {
                return this.baMessageIDField;
            }
            set {
                this.baMessageIDField = value;
                this.RaisePropertyChanged("baMessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string baCorrelationID {
            get {
                return this.baCorrelationIDField;
            }
            set {
                this.baCorrelationIDField = value;
                this.RaisePropertyChanged("baCorrelationID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mades.entsoe.eu/")]
    public partial class ReceiveMessageError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorIDField;
        
        private string errorMessageField;
        
        private string businessTypeField;
        
        private string errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("errorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string businessType {
            get {
                return this.businessTypeField;
            }
            set {
                this.businessTypeField = value;
                this.RaisePropertyChanged("businessType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
                this.RaisePropertyChanged("errorDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mades.entsoe.eu/")]
    public partial class ConfirmReceiveMessageError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorIDField;
        
        private string errorMessageField;
        
        private string messageIDField;
        
        private string errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("errorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("messageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
                this.RaisePropertyChanged("errorDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mades.entsoe.eu/")]
    public partial class ConnectivityTestError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorIDField;
        
        private string errorMessageField;
        
        private string receiverCodeField;
        
        private string errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("errorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string receiverCode {
            get {
                return this.receiverCodeField;
            }
            set {
                this.receiverCodeField = value;
                this.RaisePropertyChanged("receiverCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
                this.RaisePropertyChanged("errorDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mades.entsoe.eu/")]
    public partial class CheckMessageStatusError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorIDField;
        
        private string errorMessageField;
        
        private string messageIDField;
        
        private string errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorID {
            get {
                return this.errorIDField;
            }
            set {
                this.errorIDField = value;
                this.RaisePropertyChanged("errorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("messageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string errorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
                this.RaisePropertyChanged("errorDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mades.entsoe.eu/", ConfigurationName="MadesService.MadesEndpoint")]
    public interface MadesEndpoint {
        
        // CODEGEN: Generating message contract since the wrapper name (SendMessageRequest) of message SendMessageRequest does not match the default value (SendMessage)
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/SendMessage", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageError), Action="http://mades.entsoe.eu/SendMessage", Name="SendMessageError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageResponse SendMessage(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageResponse> SendMessageAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/ReceiveMessage", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageError), Action="http://mades.entsoe.eu/ReceiveMessage", Name="ReceiveMessageError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageResponse ReceiveMessage(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/ReceiveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageResponse> ReceiveMessageAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/ConfirmReceiveMessage", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageError), Action="http://mades.entsoe.eu/ConfirmReceiveMessage", Name="ConfirmReceiveMessageError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageResponse ConfirmReceiveMessage(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/ConfirmReceiveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageResponse> ConfirmReceiveMessageAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConnectivityTestRequest) of message ConnectivityTestRequest does not match the default value (ConnectivityTest)
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/ConnectivityTest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestError), Action="http://mades.entsoe.eu/ConnectivityTest", Name="ConnectivityTestError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestResponse ConnectivityTest(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/ConnectivityTest", ReplyAction="*")]
        System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestResponse> ConnectivityTestAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CheckMessageStatusRequest) of message CheckMessageStatusRequest does not match the default value (CheckMessageStatus)
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/CheckMessageStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusError), Action="http://mades.entsoe.eu/CheckMessageStatus", Name="CheckMessageStatusError")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusResponse CheckMessageStatus(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mades.entsoe.eu/CheckMessageStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusResponse> CheckMessageStatusAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageRequest", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SentMessage message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string conversationID;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SentMessage message, string conversationID) {
            this.message = message;
            this.conversationID = conversationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messageID;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(string messageID) {
            this.messageID = messageID;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mades.entsoe.eu/")]
    public partial class ReceivedMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        private string receiverCodeField;
        
        private string senderCodeField;
        
        private string businessTypeField;
        
        private byte[] contentField;
        
        private string senderApplicationField;
        
        private string baMessageIDField;
        
        private string baCorrelationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("messageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string receiverCode {
            get {
                return this.receiverCodeField;
            }
            set {
                this.receiverCodeField = value;
                this.RaisePropertyChanged("receiverCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string senderCode {
            get {
                return this.senderCodeField;
            }
            set {
                this.senderCodeField = value;
                this.RaisePropertyChanged("senderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string businessType {
            get {
                return this.businessTypeField;
            }
            set {
                this.businessTypeField = value;
                this.RaisePropertyChanged("businessType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string senderApplication {
            get {
                return this.senderApplicationField;
            }
            set {
                this.senderApplicationField = value;
                this.RaisePropertyChanged("senderApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string baMessageID {
            get {
                return this.baMessageIDField;
            }
            set {
                this.baMessageIDField = value;
                this.RaisePropertyChanged("baMessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string baCorrelationID {
            get {
                return this.baCorrelationIDField;
            }
            set {
                this.baCorrelationIDField = value;
                this.RaisePropertyChanged("baCorrelationID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveMessageRequest", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class ReceiveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string businessType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool downloadMessage;
        
        public ReceiveMessageRequest() {
        }
        
        public ReceiveMessageRequest(string businessType, bool downloadMessage) {
            this.businessType = businessType;
            this.downloadMessage = downloadMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveMessageResponse", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class ReceiveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceivedMessage receivedMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long remainingMessagesCount;
        
        public ReceiveMessageResponse() {
        }
        
        public ReceiveMessageResponse(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceivedMessage receivedMessage, long remainingMessagesCount) {
            this.receivedMessage = receivedMessage;
            this.remainingMessagesCount = remainingMessagesCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmReceiveMessageRequest", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class ConfirmReceiveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messageID;
        
        public ConfirmReceiveMessageRequest() {
        }
        
        public ConfirmReceiveMessageRequest(string messageID) {
            this.messageID = messageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmReceiveMessageResponse", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class ConfirmReceiveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messageID;
        
        public ConfirmReceiveMessageResponse() {
        }
        
        public ConfirmReceiveMessageResponse(string messageID) {
            this.messageID = messageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConnectivityTestRequest", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class ConnectivityTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiverCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string businessType;
        
        public ConnectivityTestRequest() {
        }
        
        public ConnectivityTestRequest(string receiverCode, string businessType) {
            this.receiverCode = receiverCode;
            this.businessType = businessType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConnectivityTestResponse", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class ConnectivityTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messageID;
        
        public ConnectivityTestResponse() {
        }
        
        public ConnectivityTestResponse(string messageID) {
            this.messageID = messageID;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mades.entsoe.eu/")]
    public partial class MessageStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        private MessageState stateField;
        
        private string receiverCodeField;
        
        private string senderCodeField;
        
        private string businessTypeField;
        
        private string senderApplicationField;
        
        private string baMessageIDField;
        
        private System.DateTime sendTimestampField;
        
        private System.Nullable<System.DateTime> receiveTimestampField;
        
        private bool receiveTimestampFieldSpecified;
        
        private MessageTraceItem[] traceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("messageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MessageState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string receiverCode {
            get {
                return this.receiverCodeField;
            }
            set {
                this.receiverCodeField = value;
                this.RaisePropertyChanged("receiverCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string senderCode {
            get {
                return this.senderCodeField;
            }
            set {
                this.senderCodeField = value;
                this.RaisePropertyChanged("senderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string businessType {
            get {
                return this.businessTypeField;
            }
            set {
                this.businessTypeField = value;
                this.RaisePropertyChanged("businessType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string senderApplication {
            get {
                return this.senderApplicationField;
            }
            set {
                this.senderApplicationField = value;
                this.RaisePropertyChanged("senderApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string baMessageID {
            get {
                return this.baMessageIDField;
            }
            set {
                this.baMessageIDField = value;
                this.RaisePropertyChanged("baMessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime sendTimestamp {
            get {
                return this.sendTimestampField;
            }
            set {
                this.sendTimestampField = value;
                this.RaisePropertyChanged("sendTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> receiveTimestamp {
            get {
                return this.receiveTimestampField;
            }
            set {
                this.receiveTimestampField = value;
                this.RaisePropertyChanged("receiveTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool receiveTimestampSpecified {
            get {
                return this.receiveTimestampFieldSpecified;
            }
            set {
                this.receiveTimestampFieldSpecified = value;
                this.RaisePropertyChanged("receiveTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("trace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MessageTraceItem[] trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("trace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mades.entsoe.eu/")]
    public enum MessageState {
        
        /// <remarks/>
        VERIFYING,
        
        /// <remarks/>
        ACCEPTED,
        
        /// <remarks/>
        DELIVERING,
        
        /// <remarks/>
        DELIVERED,
        
        /// <remarks/>
        RECEIVED,
        
        /// <remarks/>
        FAILED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mades.entsoe.eu/")]
    public partial class MessageTraceItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timestampField;
        
        private MessageTraceState stateField;
        
        private string componentField;
        
        private string componentDescriptionField;
        
        private string detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public MessageTraceState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string component {
            get {
                return this.componentField;
            }
            set {
                this.componentField = value;
                this.RaisePropertyChanged("component");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string componentDescription {
            get {
                return this.componentDescriptionField;
            }
            set {
                this.componentDescriptionField = value;
                this.RaisePropertyChanged("componentDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mades.entsoe.eu/")]
    public enum MessageTraceState {
        
        /// <remarks/>
        VERIFYING,
        
        /// <remarks/>
        ACCEPTED,
        
        /// <remarks/>
        TRANSPORTED,
        
        /// <remarks/>
        DELIVERED,
        
        /// <remarks/>
        RECEIVED,
        
        /// <remarks/>
        FAILED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckMessageStatusRequest", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class CheckMessageStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string messageID;
        
        public CheckMessageStatusRequest() {
        }
        
        public CheckMessageStatusRequest(string messageID) {
            this.messageID = messageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckMessageStatusResponse", WrapperNamespace="http://mades.entsoe.eu/", IsWrapped=true)]
    public partial class CheckMessageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mades.entsoe.eu/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MessageStatus messageStatus;
        
        public CheckMessageStatusResponse() {
        }
        
        public CheckMessageStatusResponse(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MessageStatus messageStatus) {
            this.messageStatus = messageStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MadesEndpointChannel : Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MadesEndpointClient : System.ServiceModel.ClientBase<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint>, Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint {
        
        public MadesEndpointClient() {
        }
        
        public MadesEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MadesEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MadesEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MadesEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageResponse Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint.SendMessage(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SentMessage message, string conversationID) {
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageRequest inValue = new Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageRequest();
            inValue.message = message;
            inValue.conversationID = conversationID;
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageResponse retVal = ((Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint)(this)).SendMessage(inValue);
            return retVal.messageID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageResponse> Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint.SendMessageAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageResponse> SendMessageAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SentMessage message, string conversationID) {
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageRequest inValue = new Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.SendMessageRequest();
            inValue.message = message;
            inValue.conversationID = conversationID;
            return ((Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageResponse Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint.ReceiveMessage(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageRequest request) {
            return base.Channel.ReceiveMessage(request);
        }
        
        public Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceivedMessage ReceiveMessage(string businessType, bool downloadMessage, out long remainingMessagesCount) {
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageRequest inValue = new Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageRequest();
            inValue.businessType = businessType;
            inValue.downloadMessage = downloadMessage;
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageResponse retVal = ((Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint)(this)).ReceiveMessage(inValue);
            remainingMessagesCount = retVal.remainingMessagesCount;
            return retVal.receivedMessage;
        }
        
        public System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageResponse> ReceiveMessageAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ReceiveMessageRequest request) {
            return base.Channel.ReceiveMessageAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageResponse Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint.ConfirmReceiveMessage(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageRequest request) {
            return base.Channel.ConfirmReceiveMessage(request);
        }
        
        public void ConfirmReceiveMessage(ref string messageID) {
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageRequest inValue = new Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageRequest();
            inValue.messageID = messageID;
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageResponse retVal = ((Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint)(this)).ConfirmReceiveMessage(inValue);
            messageID = retVal.messageID;
        }
        
        public System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageResponse> ConfirmReceiveMessageAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConfirmReceiveMessageRequest request) {
            return base.Channel.ConfirmReceiveMessageAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestResponse Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint.ConnectivityTest(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestRequest request) {
            return base.Channel.ConnectivityTest(request);
        }
        
        public string ConnectivityTest(string receiverCode, string businessType) {
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestRequest inValue = new Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestRequest();
            inValue.receiverCode = receiverCode;
            inValue.businessType = businessType;
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestResponse retVal = ((Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint)(this)).ConnectivityTest(inValue);
            return retVal.messageID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestResponse> Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint.ConnectivityTestAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestRequest request) {
            return base.Channel.ConnectivityTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestResponse> ConnectivityTestAsync(string receiverCode, string businessType) {
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestRequest inValue = new Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.ConnectivityTestRequest();
            inValue.receiverCode = receiverCode;
            inValue.businessType = businessType;
            return ((Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint)(this)).ConnectivityTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusResponse Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint.CheckMessageStatus(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusRequest request) {
            return base.Channel.CheckMessageStatus(request);
        }
        
        public Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MessageStatus CheckMessageStatus(string messageID) {
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusRequest inValue = new Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusRequest();
            inValue.messageID = messageID;
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusResponse retVal = ((Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint)(this)).CheckMessageStatus(inValue);
            return retVal.messageStatus;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusResponse> Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint.CheckMessageStatusAsync(Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusRequest request) {
            return base.Channel.CheckMessageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusResponse> CheckMessageStatusAsync(string messageID) {
            Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusRequest inValue = new Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.CheckMessageStatusRequest();
            inValue.messageID = messageID;
            return ((Powel.Icc.Messaging.DataExchangeManager.DataExchangeManagerService.MadesService.MadesEndpoint)(this)).CheckMessageStatusAsync(inValue);
        }
    }
}
